### ISSUE TITLE
Timeout on connect while retrieving routes/connecting

### ISSUE THREAD

**Issue by garyttierney** [ValveSoftware/GameNetworkingSockets#174] opened 2021-05-19 00:57 UTC
Hi,

Apologies if this isn't the correct place for a report (I'm using `SteamNetworkingMessages` from the Steamworks SDK).

I've been working on a small shim that can replace the older `SteamNetworking` API for legacy games and I've run into an issue setting up a symmetric connection between two clients. 

For the handshake, each client initiates a connection to each other (there's a matchmaking server instructing them to start sending packets). This appears to start fine but quickly results in a timeout shown below:

client 1
```
[2021-05-19 01:22:19.569] [modengine] [warning] Steam: Messages session steamid:76561198216541595: created
[2021-05-19 01:22:19.570] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] Our cert expires in 165312 seconds.
[2021-05-19 01:22:19.572] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] Created connection for messages session
[2021-05-19 01:22:20.317] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] Received P2P routes ack for revision 0 (latest revision is 1).
[2021-05-19 01:22:20.857] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] Received P2P routes ack for revision 0 (latest revision is 1).
[2021-05-19 01:22:21.314] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] Received P2P routes ack for revision 0 (latest revision is 1).
[2021-05-19 01:22:21.808] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] Received P2P routes ack for revision 0 (latest revision is 1).
... snip ...
[2021-05-19 01:22:29.570] [modengine] [warning] Steam: [#3971098875 P2P steamid:76561198216541595] problem detected locally (5003): App did not respond to Messages session request in time, discarding.
````

client 2
```
[2021-05-19 01:22:22.236] [modengine] [warning] Steam: Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[2021-05-19 01:22:22.237] [modengine] [warning] Steam: Destroying relay 'eat#38 (155.133.235.18:27052)' because initial_ping_timeout
[2021-05-19 01:22:24.840] [modengine] [warning] Steam: Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[2021-05-19 01:22:24.841] [modengine] [warning] Steam: Destroying relay 'eat#58 (155.133.235.34:27034)' because initial_ping_timeout
[2021-05-19 01:22:27.441] [modengine] [warning] Steam: Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[2021-05-19 01:22:27.442] [modengine] [warning] Steam: Destroying relay 'eat#37 (155.133.235.18:27051)' because initial_ping_timeout
[2021-05-19 01:22:29.565] [modengine] [warning] Steam: [#3644006119 P2P steamid:76561199104113068] problem detected locally (5003): Timed out attempting to connect
[2021-05-19 01:22:29.567] [modengine] [warning] Steam: [#3644006119 P2P steamid:76561199104113068] messages session problem detected locally: 5003 Timed out attempting to connect
```

For some additional context, the clients send each other packets at approximately the same time before either has set up a session:
client 1
```
[2021-05-19 01:22:19.562] [modengine] [info] Sending packet to 11000010f46759b
```

client 2
```
[2021-05-19 01:22:19.557] [modengine] [info] Sending packet to 1100001442db9ac
```
I have checked to see if the issue is simply that I'm not responding with `AcceptSessionWithUser(...)` when a messages session request comes in, but I've added some logging here and that callback is never invoked: https://github.com/garyttierney/ds3patch/blob/feat/ci/src/modengine_extension/p2p_session_manager.cpp#L106-L108

The only thing that really stands out to me is the ACKs for revision 0 of the routes while the latest is revision 1, but I'm not sure if that's of any importance and have little experience with the GameNetworkingSockets code so may just be a red herring. I'm also looking at the code here: https://github.com/ValveSoftware/GameNetworkingSockets/blob/f98cd32f62877d31a3fe27fc91578e13f4f795c9/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp#L2975 and there's a lot of logging that isn't present in my logs (filtering at `k_ESteamNetworkingSocketsDebugOutputType_Everything`), so maybe it's something more fundamentally wrong with how I'm setting this up.

**Comment by garyttierney** [comment] 2021-05-19 03:25
> For some additional context, the clients send each other packets at approximately the same time before either has set up a session:

This appears to be the problem, introducing an artificial delay to my first sends on one side only allows the callback to be posted. I believe I could work around this by doing some bookkeeping in my Steam lobby.

**Comment by fletcherdvalve** [comment] 2021-05-19 19:35
This is a fine place to discuss this problem!  One bit of context you might want to know: I will, hopefully soon, be updating the Steamworks SDK so that the old APIs work on top of the new infrastructure.  So the SDK will essentially contain this shim you are talking about at some point.

However, it sounds like you are basically hitting a bug in `SteamNetworkingMessages` and I'd like to understand that, if you can help me track it down.  Can you share the more detailed logs?  Note that there is configuration variable to turn on P2P-specific logging.  Try setting k_ESteamNetworkingConfig_LogLevel_P2PRendezvous to 6 (verbose)

**Comment by garyttierney** [comment] 2021-05-19 21:56
> This is a fine place to discuss this problem! One bit of context you might want to know: I will, hopefully soon, be updating the Steamworks SDK so that the old APIs work on top of the new infrastructure. So the SDK will essentially contain this shim you are talking about at some point.

Ah this is great news! I think a lot of people will be happy to hear they can use SDR and have the option to hide their IP from other peers by default. Awesome work :)

> However, it sounds like you are basically hitting a bug in SteamNetworkingMessages and I'd like to understand that, if you can help me track it down. Can you share the more detailed logs? Note that there is configuration variable to turn on P2P-specific logging. Try setting k_ESteamNetworkingConfig_LogLevel_P2PRendezvous to 6 (verbose)

Yep, I'm happy to help debug. These are the logs with P2PRendevous turned up to everything (client1 is very noisy, so saved as a gist: https://gist.github.com/garyttierney/ac438a39ede3eb9ecca3e5c7736c7ddd). Apologies if that's too much, I can repro easily and turn the logging down to verbose if there's too much noise.

Happy to do anything else I can to help. It wouldn't be too much work to port my code to using GameNetworkingSockets instead of Steamworks so I can step through or make some simple patches.

**Comment by garyttierney** [comment] 2021-05-19 22:05
Just an observation from the logs: 

client1
```
Symmetric role resolution for connect request remote cxn ID #172872179 says we should act as client.  Dropping incoming request, we will wait for them to accept ours
```

and client2:

```
Symmetric role resolution for connect request remote cxn ID #1725783370 says we should act as client.  Changing role
```

I might've misunderstood the roles in a symmetric connection, should one of them end up as `server`?

**Comment by fletcherdvalve** [comment] 2021-05-19 23:07
Looking at the source code, I think this message might be a cut and paste bug:

>Symmetric role resolution for connect request remote cxn ID #1725783370 says we should act as client.  Changing role

Both instances are in a function named "ChangeRoleToServerAndAccept", so..... 

https://github.com/ValveSoftware/GameNetworkingSockets/blob/9111a73d86cf48c47fb13862e6ecb61f75b69f6d/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_p2p.cpp#L371

**Comment by fletcherdvalve** [comment] 2021-05-19 23:24
I think the bug is that CSteamNetworkConnectionP2P::ChangeRoleToServerAndAccept does not actually do what its name says it does.  It changes the role, but it does not actually "accept" the connection.

You are reproducing this problem using the Steamworks SDK, is that right?

**Comment by garyttierney** [comment] 2021-05-19 23:54
> I think the bug is that CSteamNetworkConnectionP2P::ChangeRoleToServerAndAccept does not actually do what its name says it does. It changes the role, but it does not actually "accept" the connection.
> 
> You are reproducing this problem using the Steamworks SDK, is that right?

Yep that's right, against the latest version of the SteamNetworkingMessages interface on 1.51. I'm patching the old SteamNetworking vtable and testing against a live game so don't have a minimal test case unfortunately, but I think I could put one together that uses the SpaceWars appid as a test case if that would help. I can reproduce consistently by having both ends `SendMessageToUser(...)` to each other at the same time (within ~50ms).

**Comment by fletcherdvalve** [comment] 2021-05-20 00:02
I'm working on fixing this right now.  This *did* work at some point, I promise you!  But obviously it atrophied because it didn't really have a user, and I hadn't done the work to setup unit tests in Steam at the time.  I have since fixed that and I am right now writing unit tests for all the different cases, since these features aren't used heavily by our own games.  (For almost all of this API I just used our own games to get test coverage, but the features I'm working on now are not well covered by our games.)  I'd like to think that I would have caught this in a week or two!

It doesn't look like there is a way for me to get the fix to you.  I'll let you know when there is a new build you can test with.

**Comment by garyttierney** [comment] 2021-05-20 00:16
I appreciate the help and speedy reply! If there's anything else I can help with or more detail I can provide please let me know and I'll be happy to get it.

On a tangentially related note since you mentioned testing: if I want to set up some tests for this code that run outside of a Steam app context is the recommended approach to build against GameNetworkingSockets for tests and use the Steamworks SDK for release builds? If I've read the README correctly I think I need to use Steamworks to get access to SDR, signaling, and authentication so I can't just use GameNetworkingSocketsfor both test and release builds.

**Comment by fletcherdvalve** [comment] 2021-05-27 15:48
Hi @garyttierney The latest steam client beta has a fix (I think) for this problem.  (There were also tons of other changes under the hood not mentioned in the patch notes, including a "secret" hotkey Ctrl+\ you can press in the client to access a diagnostics panel.)

Can you check if this was fixed by opting both peers into the steam client beta?

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3032590367259099679

**Comment by garyttierney** [comment] 2021-05-27 15:53
Ah! I did spot that beta update but didn't see any NetworkingSockets/Messages things in the change notes so held off on retesting.

I can retest this in about an hour or two and will get back to you shortly, appreciate the update.

**Comment by garyttierney** [comment] 2021-05-27 21:53
I can confirm the connection is now being set up properly between the two peers, although I'm seeing issues calling `ReceiveMessaegsOnChannel(...)`. I'm getting message pointers back with all data zeroed out besides the data pointer, which is set to `1`. I'll do some double checking in my own code to make sure nothing else is going wrong here.

**Comment by garyttierney** [comment] 2021-05-27 22:07
On the above: this works fine if I call `ReceiveMessagesOnChannel` with an `nMaxMessages` of 1.

**Comment by fletcherdvalve** [comment] 2021-05-27 22:17
Can you clarify the conditions under which it misbehaves?  If you pass nMaxMessages > 1, do you sometimes get back bogus messages?

**Comment by garyttierney** [comment] 2021-05-27 22:22
Yep, that's correct. It was set to 20 before, which may have been a bit excessive.

**Comment by garyttierney** [comment] 2021-05-27 22:23
I think the original issue here is fixed, so happy to put together a new bug report and create a separate issue for that if preferred.

**Comment by fletcherdvalve** [comment] 2021-05-27 22:42
20 should be fine, and indeed a number around that magnitude is probably about right, so that you get some good "batching" and aren't pulling them out one at a time and suffering the per-call overhead for each message, but you don't have to allocate a big giant array on the stack.  What happens when you pass 20?  Are there some bogus messages returned?

Also - just to make sure we're on the same page about what this function does.  It's non-blocking, and the return value is the number of messages retrieved (which is always <= the nMaxMessages param).  So typically what you do is you call it in a loop, and you break the loop when it returns 0.  (Or, you could break it if it returns < nMaxMessages, after processing the messages, so that the loop only actually iterates if there are more than nMaxMessages pending, otherwise you only call the function once.)

**Comment by garyttierney** [comment] 2021-05-27 23:17
> 20 should be fine, and indeed a number around that magnitude is probably about right, so that you get some good "batching" and aren't pulling them out one at a time and suffering the per-call overhead for each message, but you don't have to allocate a big giant array on the stack. What happens when you pass 20? Are there some bogus messages returned?

I know there's at least one, but am crashing on the first access of a bogus message (usually on the call to `Release` which ends up doing a jump to 0x0, but have also seen a crash trying to copy from an invalid data pointer -- this doesn't always happen because the size on those bogus messages is usually 0). I'll get some more debug information and find out exactly what each message looks like.

Just for reference (or in case I'm doing something obviously wrong), here's the crashing code:

```cpp
        struct P2PInboundMessage {
            CSteamID sender;
            std::vector<char> data;
        };
 
        P2PInboundMessage current;
        SteamNetworkingMessage_t* messages = nullptr;
        auto res = steam->networking_messages->ReceiveMessagesOnChannel(0, &messages, MAX_MESSAGES /* = 20 */);

        if (res == 0) {
            std::this_thread::sleep_for(5ms);
            continue;
        }

        for (auto i = 0; i < res; i++) {
            SteamNetworkingMessage_t* message = &messages[i];

            const char* data = (char*)message->GetData();
            current.data = std::vector(data, data + message->GetSize());
            current.sender = message->m_identityPeer.GetSteamID();

            queue.push(current);
            message->Release();
        }
```

**Comment by fletcherdvalve** [comment] 2021-05-27 23:22
You need to pass in an array.  Try declaring it like this:

SteamNetworkingMessage_t* messages[ MAX_MESSAGES ];

**Comment by garyttierney** [comment] 2021-05-27 23:31
> You need to pass in an array. Try declaring it like this:
> 
> SteamNetworkingMessage_t* messages[ MAX_MESSAGES ];

Ah! A silly oversight, that makes sense 🤦.

Appreciate all the help, and apologies for the bogus report. Can confirm everything's working as expected here. Great work on the library!

**Comment by fletcherdvalve** [comment] 2021-05-27 23:33
Great!

**Closed by fletcherdvalve** 2021-05-27 23:33 UTC
Labels: Need Retest, bug
