### ISSUE TITLE
steamclient.dll is using broken version of openssl libs

### ISSUE THREAD

**Issue by SDGNelson** [ValveSoftware/GameNetworkingSockets#148] opened 2020-10-09 20:58 UTC
We just rolled out SteamNetworkingSockets as the new default for Unturned (AppId 304930) and it is working well for most players. Unfortunately after `ConnectByIPAddress` a minority of clients are entering the `ProblemDetectedLocally` state with error code 4003 and debug message:

"Bad cert: CA key ### is not known to us"
(e.g. key 18220590129359924542)

Before `ConnectByIPAddress` we wait for the `k_ESteamNetworkingAvailability_Current` availability callback, so as far as I can tell we should be ready for authenticated connection. There are other players connected to these same servers, so I assume the certs were known to them.

Are we missing a step to have the proper certs before connecting?
If you can share any thoughts that would be greatly appreciated.

Kind regards,
Nelson

**Comment by SDGNelson** [comment] 2020-10-09 22:31
It seems consistent for certain players. I believe all of these reports so far are on Windows, but based on your question I will ask about consistency and platform.

**Comment by fletcherdvalve** [comment] 2020-10-09 23:01
You might also ask if they are on laptops.

Here is the relevant bug.  (If this is indeed the bug I am thinking of.)
https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html

Also, just to confirm --- this is the Steam version, correct?  So your players are getting the ISteamNetworkingSockets code in steamclient.dll that ships with the Steam client?

If this is the bug I think it is, the problem is caused if you somehow load up a busted version of the openssl .dll, and then when we go to initialize openssl, it uses that one instead of the good one we ship with Steam.

**Comment by SDGNelson** [comment] 2020-10-09 23:16
Fortunately since you mentioned laptops in your original comment I included that in my question to them. Only one player has responded so far, but they have said they are using a Windows laptop.

Yes, this is the Steam version.

Since you mention the steamclient.dll I think you could be onto that as the issue: we have a copy of steamclient.dll bundled with the game files which must be out-of-date. I will remove that in a patch momentarily.

The reason steamclient.dll was bundled with the game files is prior to the game having a dedicated server app players needed the dedicated server redist files, so they were kept around for backwards compatibility. Most hosts have transitioned to the dedicated server app by now, so it should be safe to delete.

Thank you for your time! I will let you know how the patch goes.

**Comment by fletcherdvalve** [comment] 2020-10-09 23:18
Ah!  Yes, if it is using an old version of steamclient.dll that still has the bug, that could be bad.  If it is getting loaded.  I think that we specifically locate the steamclient.dll that is being used by the running steam client, though.  I'm installing your game now and just stepping into the code that that should initialize the cert store, and see exactly what openssll code is being used.

**Comment by fletcherdvalve** [comment] 2020-10-09 23:37
Stepping into your app, it looks like it is using the openssl code from our .dll.  So I might be off base here.  But the problems just do see really similar to previous problems like this.

And that steamclient.dll64 you are distributing is from September of this year, which is very recent.  (But in general it's best to not ship that, or vstdlib_s or tier0_s, to clients.)

I didn't run the battle eye version of the game.  They could be doing stuff that I might not be able to understand.

**Comment by fletcherdvalve** [comment] 2020-10-09 23:42
I think this is a regression on our side.  Standby.

**Comment by SDGNelson** [comment] 2020-10-09 23:44
Thanks for taking a look.

If we are lucky then hopefully it was BattlEye redirecting to the bundled steamclient, in which case it will hopefully be fixed now that it has been deleted.

In the patch I removed vstdlib_s and tier0_s as well, and will fully deprecate hosting the dedicated server via the client (in favor of the standalone dedicated server app).

**Comment by fletcherdvalve** [comment] 2020-10-09 23:54
OK, I confirmed that we regressed steamclient.dll and started shipping the busted version of opensll at some point.  We'll get this fixed ASAP, probably early next week.

**Comment by SDGNelson** [comment] 2020-10-09 23:59
Thank you! I will notify the affected players.

In the meantime we have a command-line flag which enables `k_ESteamNetworkingConfig_IP_AllowWithoutAuth` for the initial options passed into `ConnectByIPAddress`. Should I recommend that they enable this command-line option as a workaround, i.e would it bypass error 4003?

**Comment by fletcherdvalve** [comment] 2020-10-10 00:05
To be honest, I could not say for sure if "cert is bad" is handled the same way as "no cert" with respect to that flag.

**Comment by SDGNelson** [comment] 2020-10-10 00:10
Fair enough. I will suggest it as a potential workaround.

**Comment by SingleThreadedWorld** [comment] 2020-10-14 08:23
Any update on this? Don't mean to sound impatient or anything, but early next week is getting there.

Thanks for your time

**Comment by QnAisbest** [comment] 2020-10-14 11:35
I am going to just add that 2 people have told me they got this issue on desktop computers in unturned.

**Comment by jatapa** [comment] 2020-10-14 11:36
I am going to just add that 2 people have told me they got this issue on desktop computers in unturned.

**Comment by fletcherdvalve** [comment] 2020-10-19 20:46
This fix has been released to the default public client.

https://store.steampowered.com/news/76713/

**Closed by fletcherdvalve** 2020-10-19 20:46 UTC
Labels: steamworks
