### ISSUE TITLE
Compiling under Windows with MinGW

### ISSUE THREAD

**Issue by nxrighthere** [ValveSoftware/GameNetworkingSockets#11] opened 2018-04-01 10:46 UTC
Does someone have success? The compiler throws a lot of errors. I'm currently trying to fix them, but there are too many. The code itself in some places is questionable like [here](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/common/crypto.cpp#L401) and [here](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/common/crypto.cpp#L3081).

**Comment by tycho** [comment] 2018-04-01 10:50
No, it doesn't build under MinGW/MSYS2 yet. I was working on this just before we pushed code publicly, but my changes aren't ready for consumption yet. I intend to work on it this week.

The majority of the issues are centered around macro misuse caused by bad assumptions, such as: _WIN32/WIN32 means we "must" be compiling on Visual Studio, and that __GNUC__ means we "must" be compiling on something non-Windows.

**Comment by nxrighthere** [comment] 2018-04-01 10:52
Yea I see, I'm glad that you are working on it. Thank you.

**Comment by AraHaan** [comment] 2018-04-01 20:04
well there are special macros for cygwin and mingw that also defines _WIN32 I thought. So maybe something like this would suffice
#if defined(_WIN32) && (defined(__GNUC__) /*|| optionally include clang windows build. */) && (__cygwin__ || __mingw__)

or something around those lines.

**Comment by tycho** [comment] 2018-04-02 20:14
Probably fixed with https://github.com/ValveSoftware/GameNetworkingSockets/commit/7db463285bbd64b34ed21dbf86986c87d34b5d66

But it also probably has bugs. Let me know if you find some!

**Closed by tycho** 2018-04-02 20:14 UTC

**Comment by nxrighthere** [comment] 2018-04-02 21:25
@tycho There is still no success:

```
GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsockets_certtool.cpp: In function 'void PrintCertInfo(const CMsgSteamDatagramCertificateSigned&, std::__cxx11::string&, const char*)':
GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsockets_certtool.cpp:204:45: error: expected ')' before 'PRIu64'
   V_sprintf_safe( szTemp, "%s\"key_id\": %" PRIu64 ",\n", pszJSONIndent, CalculatePublicKeyID( pubKey ) );
                                             ^~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsockets_certtool.cpp:215:48: error: expected ')' before 'PRIu64'
   V_sprintf_safe( szTemp, "%s\"ca_key_id\": %" PRIu64 "\n", pszJSONIndent, msgSigned.ca_key_id() );
                                                ^~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsockets_certtool.cpp:220:50: error: expected ')' before 'PRIu64'
   V_sprintf_safe( szTemp, "Public key ID. . : %" PRIu64 "\n", CalculatePublicKeyID( pubKey ) );
                                                  ^~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsockets_certtool.cpp:226:50: error: expected ')' before 'PRIu64'
   V_sprintf_safe( szTemp, "CA key ID. . . . : %" PRIu64 "\n", msgSigned.ca_key_id() );
```

Solved this with `#define PRIu64 "I64u"`.

But the next one is more fun:

```
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1318:53: error: function 'ISteamNetworkingSockets* SteamNetworkingSockets()' definition is marked dllimport
 STEAMDATAGRAMLIB_INTERFACE ISteamNetworkingSockets *SteamNetworkingSockets()
                                                     ^~~~~~~~~~~~~~~~~~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: In function 'ISteamNetworkingSockets* SteamNetworkingSockets()':
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1318:53: warning: 'ISteamNetworkingSockets* SteamNetworkingSockets()' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: At global scope:
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1323:53: error: function 'ISteamNetworkingSockets* SteamNetworkingSocketsGameServer()' definition is marked dllimport
 STEAMDATAGRAMLIB_INTERFACE ISteamNetworkingSockets *SteamNetworkingSocketsGameServer()
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: In function 'ISteamNetworkingSockets* SteamNetworkingSocketsGameServer()':
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1323:53: warning: 'ISteamNetworkingSockets* SteamNetworkingSocketsGameServer()' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: At global scope:
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1330:33: error: function 'bool GameNetworkingSockets_Init(char (&)[1024])' definition is marked dllimport
 STEAMDATAGRAMLIB_INTERFACE bool GameNetworkingSockets_Init( SteamDatagramErrMsg &errMsg )
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: In function 'bool GameNetworkingSockets_Init(char (&)[1024])':
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1330:33: warning: 'bool GameNetworkingSockets_Init(char (&)[1024])' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: At global scope:
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1342:33: error: function 'void GameNetworkingSockets_Kill()' definition is marked dllimport
 STEAMDATAGRAMLIB_INTERFACE void GameNetworkingSockets_Kill()
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp: In function 'void GameNetworkingSockets_Kill()':
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp:1342:33: warning: 'void GameNetworkingSockets_Kill()' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
```

**Comment by tycho** [comment] 2018-04-02 21:27
How are you building? Are you using MSYS2 or some other version of MinGW?

http://www.msys2.org/

**Comment by nxrighthere** [comment] 2018-04-02 21:28
Solved this one with `#define STEAMDATAGRAMLIB_FOREXPORT 1`.

Moving forward:
```
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp:1685:33: error: function 'void SteamDatagram_SetDebugOutputFunction(int, FSteamDatagramDebugOutput)' definition is marked dllimport
 STEAMDATAGRAMLIB_INTERFACE void SteamDatagram_SetDebugOutputFunction( /* ESteamDatagramSpewType */ int eDetailLevel, FSteamDatagramDebugOutput pfnFunc )
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp: In function 'void SteamDatagram_SetDebugOutputFunction(int, FSteamDatagramDebugOutput)':
GameNetworkingSockets\src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp:1685:33: warning: 'void SteamDatagram_SetDebugOutputFunction(int, FSteamDatagramDebugOutput)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
```

**Comment by nxrighthere** [comment] 2018-04-02 21:30
I building it with [Mingw-w64](https://mingw-w64.org/doku.php).

**Comment by tycho** [comment] 2018-04-02 21:32
Try using MSYS2 instead.

Also STEAMDATAGRAMLIB_FOREXPORT is already defined in meson.build -- how are you building?

**Comment by nxrighthere** [comment] 2018-04-02 21:35
I just created CMakeLists since I'm not using Meson. Well, I'll try to build it with MSYS2 if I don't solve all these errors myself.

**Comment by tycho** [comment] 2018-04-02 21:36
Or take a look at the meson.build changes and copy them over to your CMakeLists.txt

**Comment by nxrighthere** [comment] 2018-04-02 21:39
Yea, I missed some stuff there actually... Thank you.
