### ISSUE TITLE
Increasing throughput of a connection

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#198] opened 2021-10-26 14:55 UTC
Hello,

On a localhost I get around 1MB/s with the default config options. I am trying to reach 10MB/s.

So far I have only found the SendRateMax option that could be limiting, increasing it to a much larger value gets me to 1.2MB/s.
Changing the send buffer size doesn't seem to help. Is this a limitation due to the way the protocol is designed or am I missing something?

Thanks,
Max

**Comment by fletcherdvalve** [comment] 2021-10-29 23:57
I haven't forgotten about this....  I wanted to finish the multi lane support first, which I just now did  Will look at this soon, but it might be next week.

**Comment by fletcherdvalve** [comment] 2021-11-02 23:57
I apologize that I still have not been able to work on testing the sample you sent me.  I'll keep this bug open until I am able to look at it.  I did add a throughput test that sends reliable data at 8MBytes / sec, though, so I am pretty sure there's nothing inherent in the lib that can't handle high throughput.  It's gotta be something in the C# layer or the way it's being driven.

**Comment by fletcherdvalve** [comment] 2021-11-03 00:35
Hm, I've reproduced some problems going above 8MB, which is where I arbitrarily stopped in my test.  I'll let you know when I get to the bottom of it.

**Comment by fletcherdvalve** [comment] 2021-11-05 20:57
Are you compiling a release build?  Can you see what happens if you compile in release and make sure STEAMNETWORKINGSOCKETS_SNP_PARANOIA=0?  In my case, I realized that this paranoia code constantly checking the integrity of internal data structures was taking a ton of CPU time, and we couldn't keep up.

I also checked in a change to tweak how to limit the number of packets sent in a single burst.  (See 4a2c2cc36458d0536fec7ede426f75b15323a744).  After making sure the paranoia checks are off (which I think should be the case by default in a release build, but please verify this...) and then with this change, I'm seeing 60MB / sec on my windows and linux VM.  Would be curious what you are able to get, if you just run the latest code in release.  Hopefully you can get high throughput just with the code as-is.  but one last thing to tweak would be to try increase g_cbUDPSocketBufferSize 

Also there is now a throughput test.  It uses network loopback, but this is actually less optimal than two clients, since one thread has to do all the encryption / decryption work, whereas if you actually had two different processes for server and client they would each get their own CPU for this work.

https://github.com/ValveSoftware/GameNetworkingSockets/runs/4121732894?check_suite_focus=true#step:6:2170

**Comment by fletcherdvalve** [comment] 2021-11-07 23:04
Closing this for now -- lemme know if you find anything

**Closed by fletcherdvalve** 2021-11-07 23:04 UTC
Labels: Need Retest
