### ISSUE TITLE
cmake install() steps broken when building with WebRTC

### ISSUE THREAD

**Issue by unalkalkan** [ValveSoftware/GameNetworkingSockets#138] opened 2020-09-12 18:05 UTC
I am trying to build GNS with **USE_STEAMWEBRTC** and **STEAMWEBRTC_USE_STATIC_LIBS** ON and CMake is giving me this error:
```
D:\Workspace\GameNetworkingSockets-webrtc\GameNetworkingSockets\build>cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
-- MSVC -> forcing use of dynamically-linked runtime.
-- Initial build flags:
--   'CMAKE_C_FLAGS_DEBUG': /MDd /Zi /Ob0 /Od /RTC1
--   'CMAKE_C_FLAGS_MINSIZEREL': /MD /O1 /Ob1 /DNDEBUG
--   'CMAKE_C_FLAGS_RELEASE': /MD /O2 /Ob2 /DNDEBUG
--   'CMAKE_C_FLAGS_RELWITHDEBINFO': /MD /Zi /O2 /Ob1 /DNDEBUG
--   'CMAKE_CXX_FLAGS_DEBUG': /MDd /Zi /Ob0 /Od /RTC1
--   'CMAKE_CXX_FLAGS_MINSIZEREL': /MD /O1 /Ob1 /DNDEBUG
--   'CMAKE_CXX_FLAGS_RELEASE': /MD /O2 /Ob2 /DNDEBUG
--   'CMAKE_CXX_FLAGS_RELWITHDEBINFO': /MD /Zi /O2 /Ob1 /DNDEBUG
--
-- No CMAKE_CXX_STANDARD set, assuming 11
-- Crypto library for AES/SHA256: libsodium
-- Crypto library for ed25519/curve25519: libsodium
-- Configuring done
CMake Error: install(EXPORT "GameNetworkingSockets" ...) includes target "GameNetworkingSockets" which requires target "steamwebrtc" that is not in the export set.
CMake Error: install(EXPORT "GameNetworkingSockets" ...) includes target "GameNetworkingSockets_s" which requires target "steamwebrtc" that is not in the export set.
-- Generating done
-- Build files have been written to: D:/Workspace/GameNetworkingSockets-webrtc/GameNetworkingSockets/build
```
And since it couldn't build properly, typing ninja gives this one:
```
D:\Workspace\GameNetworkingSockets-webrtc\GameNetworkingSockets\build>ninja
ninja: error: loading 'build.ninja': The system cannot find the file specified.
```

I have tried this on Windows with libsodium and on freshly created Debian 10 Droplet with OpenSSL, they both gave me this error so I thought its not about something I have done

**Comment by fletcherdvalve** [comment] 2020-09-15 01:07
Static linking really needs to be the only option.  There is no reason why anybody would want to link dynamically.

I'm hitting that same issues you hit when making that change, though.  So I'll need some help, probably from @tycho

**Comment by fletcherdvalve** [comment] 2020-09-15 01:43
OK, I just removed that option.  And now we always static link.

And I added an if() to just comment out the install steps if P2P is enabled, for now.  I renamed the bug to clarify exactly what the problem is.

**Comment by fletcherdvalve** [comment] 2020-10-07 16:51
I believe this is fixed now.

**Closed by fletcherdvalve** 2020-10-07 16:51 UTC
Labels: help wanted
