### ISSUE TITLE
Exception Running Example

### ISSUE THREAD

**Issue by csulmone** [ValveSoftware/GameNetworkingSockets#57] opened 2019-03-17 22:04 UTC
chriss-mbp:build chris$ ./examples/example_chat server
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6

Looks like the exception is coming from here:
https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp#L73

I am running with the release 1.0.0 code on OSX with the latest clang and openssl 1.1.1.

**Comment by kkukshtel** [comment] 2019-03-27 23:52
I'm getting the same issue on OSX when using the compiled dylib with [the C# wrapper](https://github.com/nxrighthere/ValveSockets-CSharp)

Here's the trace:

```
Application Specific Information:
libGameNetworkingSockets.dylib
abort() called
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

Thread 0 Crashed:: tid_307  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5e783b66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5e94e080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff5e6df1ae abort + 127
3   libmonobdwgc-2.0.dylib        	0x000000013e5aa4b2 mono_handle_native_crash + 585
4   libsystem_platform.dylib      	0x00007fff5e941f5a _sigtramp + 26
5   com.unity3d.UnityEditor5.x    	0x0000000100020008 floor1_encode + 696
6   libsystem_c.dylib             	0x00007fff5e6df1ae abort + 127
7   libc++abi.dylib               	0x00007fff5c5d9f8f abort_message + 245
8   libc++abi.dylib               	0x00007fff5c5da113 default_terminate_handler() + 241
9   libobjc.A.dylib               	0x00007fff5da1beab _objc_terminate() + 105
10  libc++abi.dylib               	0x00007fff5c5f57c9 std::__terminate(void (*)()) + 8
11  libc++abi.dylib               	0x00007fff5c5f526f __cxa_throw + 121
12  libc++.1.dylib                	0x00007fff5c5c87af std::__1::__throw_system_error(int, char const*) + 77
13  libc++.1.dylib                	0x00007fff5c5bac93 std::__1::mutex::lock() + 29
14  libc++.1.dylib                	0x00007fff5c5bb118 std::__1::recursive_timed_mutex::lock() + 42
15  libGameNetworkingSockets.dylib	0x0000000120635a40 SteamNetworkingSocketsLib::SteamDatagramTransportLock::Lock() + 16 (steamnetworkingsockets_lowlevel.cpp:75)
16  libGameNetworkingSockets.dylib	0x0000000120626f95 SteamNetworkingSocketsLib::EnsureConfigValueTableInitted() + 53 (steamnetworkingsockets_lowlevel.h:354)
17  libGameNetworkingSockets.dylib	0x000000012062761f SteamNetworkingSocketsLib::CSteamNetworkingSockets::CSteamNetworkingSockets() + 447 (vector:1471)
18  libGameNetworkingSockets.dylib	0x000000012062cd48 _GLOBAL__sub_I_csteamnetworkingsockets.cpp + 2360 (csteamnetworkingsockets.cpp:1239)
```

**Comment by fletcherdvalve** [comment] 2019-03-28 01:54
I believe this should be fixed, but not 100% sure since I never did reproduce it.

Fixed?

**Comment by kkukshtel** [comment] 2019-03-28 03:31
@fletcherdvalve Looks like this is fixed on my end! Just pulled and recompiled and am not seeing any crashes. I'm not rigorously testing it against anything but for my case it seems fixed.

**Comment by fletcherdvalve** [comment] 2019-03-28 18:25
Cool, thanks!

**Closed by fletcherdvalve** 2019-03-28 18:25 UTC
