### ISSUE TITLE
P2P realiable packages extremely lossy when high throughput (even on localhost)

### ISSUE THREAD

**Issue by gtnardy** [ValveSoftware/GameNetworkingSockets#226] opened 2022-05-29 10:38 UTC
Hello there, I'm not sure if GameNetworkingSockets and Steamworks version are interchangeable and the implementation is shared, but as I used to use the open source version and recently moved to the Steamworks I'm posting it here 😁

I'm going through some problems when using P2P servers (using Steam Relay - on the steamworks version). When I set the `SendRateMin` config to anything bigger than **1 MB** and send lots of reliable data to the client (more than **1 MB/s**), I start getting like up to 80% of packet drop on the client side and lots of logs spamming on my console, like the following. Note: I'm connected to localhost (through SDR),

```cpp
SteamNetworkingConfigValue[0].SetInt32(k_ESteamNetworkingConfig_SendRateMin, 0x800000); // 8 MB
```

```
[#4212214575 P2P SDR steamid:90159582887391236@169.254.204.197:44376] decode pkt 29368 abort.  Reliable stream already has 30 fragments, first is [1950284,2056973), last is [2519880,2530113).  We don't want to fragment [1950284,2056973) with new segment [1957106,1958243)

[#4212214575 P2P SDR steamid:90159582887391236@169.254.204.197:44376] decode pkt 31054 abort.  Reliable stream already has 30 fragments, first is [1950284,2055836), last is [2557401,2561949), new segment is [2630317,2631454)

[#4212214575 P2P SDR steamid:90159582887391236@169.254.204.197:44376] decode pkt 11814 abort.  839957 bytes reliable data buffered [756982-1596939), new size would be 1251289 to 2008271
```

I've dug a bit and found that they seem to come from the malicious sender algorithm preventer, but I'm just not sure if this only happens because of the SDR connection (which because of the route it makes it to lose or disorder packets) or because of the P2P itself. Because starting it normally (with `CreateListenSocketIP`) I can send almost infinite reliable data without loss neither that logs.

As I'm on the steamworks version, I can't tweak the parameters used to define if it should discard the packages, because it is not exposed to the steamworks headers neither as a config parameter:

```cpp
constexpr int k_cbMaxBufferedReceiveReliableData = k_cbMaxMessageSizeRecv + 64*1024;
constexpr int k_nMaxReliableStreamGaps_Extend = 30; // Discard reliable data past the end of the stream, if it would cause us to get too many gaps
constexpr int k_nMaxReliableStreamGaps_Fragment = 20; // Discard reliable data that is filling in the middle of a hole, if it would cause the number of gaps to exceed this number
constexpr int k_nMaxPacketGaps = 62; // Don't bother tracking more than N gaps.  Instead, we will end up NACKing some packets that we actually did receive.  This should not break the protocol, but it protects us from malicious sender
```

Thank you in advance, hope that makes any sense 😅

**Comment by zpostfacto** [comment] 2022-05-31 17:30
Do you have issues when you connect via plain IP?

Here are some potential issues:

1.) The relays *do* enforce a rate limit, and right now it is essentially hardcoded.  We don't have a way for the peers to negotiate raising the limit, or for the peers to even know what limit the relay is actually going to use, if a relay declines to relay at a rate as high as you request.  So if the problem doesn't happen with plain IP, that could be the cause.

2.) There were some bugs related to this that were recently fixed.  Make sure you have those fixes.  Relevant links:
https://github.com/ValveSoftware/GameNetworkingSockets/commit/a39de80f9b53d20ecdfada8935e16c9279882d03
https://store.steampowered.com/oldnews/138198

Hm, now that I type this, I realize that this fix has not been deployed to the dedicated server redistributables.  If your app is getting steamclient.dll/so through the dedicated server redistributables, it might not have the fix yet.  Just replace the steam binaries with the ones from your steam client temporarily to rule this out as a cause.

3.) In general, the protocol has flaws that lead to poor performance when the send rate and packet loss are both relatively high, especially if latency is also high.  I have a plan to address this, but there are relatively few use cases that hit this problem, so I haven't yet invested the time.  Let's rule out #1 and #2 before we decide that you are having problems with this, though.

**Comment by gtnardy** [comment] 2022-05-31 21:05
Hey, thank you for the answer!

The `1)` makes sense, as anything beyond 1 MB seems to start getting messy. Although the package drop occurs on the client/receiver peer (unless the relay is dropping some of them as well causing a cascade effect?). It seems to be limiting it to 1MB and/or to 1.000.000 packets received per second (I could see it with `GetConnectionRealTimeStatus()`)

Indeed I don't have issues with plain IP (`CreateListenSocketIP`), it's speed is almost as much as it can handle. This issue comes only with P2P (`CreateListenSocketP2P`).

Hmm got it about the `2)`, actually on my dedicated server (and on my client) I just use the `steam_api64.dll` (which comes with the SDK) and this doesn't seem to exist in the Steam client folder 🤔. The `steamclient64.dll` ones are not used by my server which is built with the SDK.

The last Steamworks SDK update was on [Dec 11, 2021](https://partner.steamgames.com/downloads/list), it most likely was not deployed in there 😜.

Looking forward to that fix to see if that's the causer of that

**Comment by zpostfacto** [comment] 2022-06-15 13:41
The fix has been deployed ti the dedicated server redistributables.  I dont really see any indication it was involved, though, this just looks like a case where the relays are rate limiting you.

I want to improve the negotiation of the rate limit with the relays but there will probably always be one, as we need that yi avoid abuse if this free service.

**Closed by zpostfacto** 2022-06-15 13:41 UTC
